services:
  # Telegram Bot
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: remnawave-market-bot
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      TELEGRAM_API_URL: http://remnawave-market-app:3000/api/v1
      NODE_ENV: ${NODE_ENV:-production}
    networks:
      - remnawave-market_remnawave-network

networks:
  remnawave-market_remnawave-network:
    external: true
